### ISSUE TITLE
src/scripts are not available in the manual setup link

### ISSUE THREAD

**Issue by kirank5** [Azure/cortana-intelligence-customer360#4]
Hi,

    I am not able to find src/scripts (powershell / ARM) to deploy the solution manually. Could you please fix it ?

Thanks,
Kiran

**Comment by awaemmanuel** [comment]
Thank you for your  comment. We'll look into this.

**Comment by awaemmanuel** [comment]
Hi @kirank5 , 

With the way the solution template is setup and the new approach to surfacing these templates, we've decided to make deployment easier for the end-user via the automated  deploy experience.  Please find how to deploy [here](https://github.com/Azure/cortana-intelligence-customer360/blob/master/Technical%20Deployment%20Guide/README.md#solution-setup). 
The tutorial has also been modified to reflect this. Thank you for pointing this out.
